[package]
name = "rocketcamel/fastcastredux"
description = "A Fork of FastCastRedux which allows for casting models."
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["rocketcamel"]

[dependencies]